### ISSUE TITLE
Tax on shipping not being calculated in the cart

### ISSUE THREAD

**Issue by emilioTejada** [bobbingwide/oik-weight-zone-shipping#33]
Hi! The shipping tax is not applied to the cart, even if it has been configured as taxable in the Multi Rate Weight Zone settings

oik weight zone shipping: 0.25
Woocommerce: 7.3.0
Wordpress: 6.1.1
PHP: 7.4.33

Thanks.

**Comment by bobbingwide** [comment]
Hi, can you give examples of what you expect to happen. Then I'll be able to reproduce.

**Comment by emilioTejada** [comment]
Of course.

This is a example of order. 

![image](https://user-images.githubusercontent.com/15647702/213683317-a6c6a1f9-c51b-4149-a660-9a5f359035fd.png)

This is the Multi Rate Weight Zone settings

![image](https://user-images.githubusercontent.com/15647702/213683678-4bb31647-4bdf-4caa-8728-d3269cc50760.png)

In the cart only have the tax of the product, not of the shipment

Thanks for your time.

**Comment by emilioTejada** [comment]
Hi again. I have news.

I had this tax setup. In this way, the shipping tax was not calculated in the cart.

![image](https://user-images.githubusercontent.com/15647702/213690506-2824ac69-f617-4bea-afeb-fefee8d5b022.png)

But when removing the first row, it already appears with the calculated tax

![image](https://user-images.githubusercontent.com/15647702/213690772-baf91996-4e4a-42b2-a1c1-5a68270752b4.png)

**Comment by bobbingwide** [comment]
> But when removing the first row, it already appears with the calculated tax

Does that mean you've resolved the problem?

**Comment by emilioTejada** [comment]
Yes it already works as expected, but only when there is a tax line. What I don't understand is why, when there are 2 taxes configured, it was not calculated with any of them. I think I had them set up right.

**Comment by bobbingwide** [comment]
> What I don't understand is why, when there are 2 taxes configured, it was not calculated with any of them. 

Sorry that it's taken so long for me to follow up on this. I believe you had resolved your problem in January.

![image](https://github.com/bobbingwide/oik-weight-zone-shipping/assets/2474435/d2deee77-841a-4523-95cb-e5095f0d44da)

I believe your problem is that you had used the same Priority for the two tax rates. The first one was being used and this didn't include Shipping.  

I figured this after reading [Setting up taxes in WooCommerce](https://woocommerce.com/document/setting-up-taxes-in-woocommerce/)
